import re
s='昔人已乘黃鶴去，此地空余黃鶴樓。\
黃鶴一去不復返，白雲千載空悠悠。'
print(s)
ans = re.findall('[一去]?', s)
print('[一去]?', ans)
ans = re.findall('[一去]*', s)
print('[一去]*', ans)
ans = re.findall('[一去]*?', s)
print('[一去]*?', ans)
ans = re.findall('[黃鶴樓]+',s)
print('[黃鶴樓]+', ans)
ans = re.findall('[黃鶴樓]+?',s)
print('[黃鶴樓]+?', ans)
ans = re.findall('[黃鶴樓]{2}',s)
print('[黃鶴樓]{2}', ans)
ans = re.findall('[黃鶴樓]{1,2}',s)
print('[黃鶴樓]{1,2}', ans)
ans = re.findall('[黃鶴樓]{1,2}?',s)
print('[黃鶴樓]{1,2}?', ans)
ans = re.findall('黃鶴(?=樓)',s)
print('黃鶴(?=樓)', ans)
ans = re.findall('黃鶴(?!樓)',s)
print('黃鶴(?!樓)', ans)
ans = re.findall('(?<=黃鶴)樓',s)
print('(?<=黃鶴)樓', ans)
ans = re.findall('(?<!黃鶴)樓',s)
print('(?<!黃鶴)樓', ans)